# Generated by Django 5.2.12 on 2026-04-21 20:28

import django.db.models.deletion
import remote_app.models
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryContext',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp_created', models.FloatField(default=time.time)),
                ('timestamp_modified', models.FloatField(default=time.time)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'entry_context',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(default=remote_app.models._new_entry_id, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('timestamp_created', models.FloatField(default=time.time)),
                ('timestamp_modified', models.FloatField(default=time.time)),
                ('deleted_at', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='remote_app.entry')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='remote_app.entrycontext')),
            ],
            options={
                'db_table': 'entry',
            },
        ),
        migrations.CreateModel(
            name='EntryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(default='unknown', max_length=100)),
                ('timestamp', models.FloatField(default=time.time)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='remote_app.entry')),
            ],
            options={
                'db_table': 'entry_version',
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['kind', '-timestamp_created'], name='entry_kind_b71943_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['context', 'kind', '-timestamp_created'], name='entry_context_67ee85_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['archived'], name='entry_archive_579b73_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['status'], name='entry_status_cc9d43_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('context', 'name'), name='uniq_context_name'),
        ),
        migrations.AddIndex(
            model_name='entryversion',
            index=models.Index(fields=['entry', '-timestamp'], name='entry_versi_entry_i_4ca17c_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryversion',
            constraint=models.UniqueConstraint(fields=('entry', 'version_num'), name='uniq_entry_version_num'),
        ),
    ]
