# Generated by Django 5.2.12 on 2026-04-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmFiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=200)),
                ('dedupe_key', models.CharField(max_length=400)),
                ('first_fired_at', models.DateTimeField()),
                ('last_fired_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'active'), ('cleared', 'cleared')], default='active', max_length=16)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('recipients', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alarm_firing',
                'indexes': [models.Index(fields=['state', '-last_fired_at'], name='alarm_firin_state_3af375_idx'), models.Index(fields=['check_name', '-last_fired_at'], name='alarm_firin_check_n_c51b87_idx')],
                'constraints': [models.UniqueConstraint(fields=('check_name', 'dedupe_key'), name='uniq_alarm_firing_key')],
            },
        ),
        migrations.CreateModel(
            name='AlarmRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checks_run', models.IntegerField(default=0)),
                ('alarms_seen', models.IntegerField(default=0)),
                ('notifications_sent', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'alarm_run',
                'indexes': [models.Index(fields=['-started_at'], name='alarm_run_started_97fc0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlarmFiringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('action', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('firing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='remote_app.alarmfiring')),
            ],
            options={
                'db_table': 'alarm_firing_event',
                'indexes': [models.Index(fields=['firing', '-ts'], name='alarm_firin_firing__f37aba_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlarmCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('alarms_seen', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('params_snapshot', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='remote_app.alarmrun')),
            ],
            options={
                'db_table': 'alarm_check_run',
                'indexes': [models.Index(fields=['check_name', '-started_at'], name='alarm_check_check_n_45050c_idx')],
            },
        ),
    ]
