# Generated by Django 5.2.12 on 2026-09-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('remote_app', '0009_teamcomms_service_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='authority_status', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('github', models.CharField(blank=True, default='', max_length=100)),
                ('eic', models.BooleanField(null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('failed', models.CharField(blank=True, default='', max_length=500)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authority_status',
            },
        ),
    ]
